## Default spring settings
server.port: 9090

# Project specific properties
uservist:
  host: http://127.0.0.1
  allowedOrigins:
    - http://localhost:9080
    - http://192.168.0.11:9080
  serviceKey: a148d971d156a65538dc0ae8ac9faf9563b4201e33429ddcd5b346fbdbfc8997
  tokenName: Authorization
  tokenPrefix: "Bearer "

## Spring settings
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    # Database connection settings
    url: jdbc:postgresql://localhost:5432/uservist
    username: postgres
    password: postgres
    jpa.properties.hibernate.default_schema: uservist

  # Mail sending settings
  mail:
    host: smtp.gmail.com
    port: 587

    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true

    scheduler:
      persistence:
        enabled: false
        redis.embedded: false
        redis.enabled: false
