## Default spring settings
server.port: 9090

# Project specific properties
uservist:
  host: http://127.0.0.1
  tokenSigningKey: lF7hHKrfm3gHYlNc6L2FBuif0apReq34SFYdbPuIGag
  tokenName: Authorization
  tokenPrefix: "Bearer "
  tokenValidity: 86400

## Spring settings
spring:
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties.hibernate.default_schema: uservist
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres

    # Database connection settings
    url: jdbc:postgresql://192.168.0.28:5632/uservist
    username: postgres
    password: 17931548625

  # Mail sending settings
  mail:
    host: smtp.gmail.com
    port: 587

    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true

    scheduler:
      persistence:
        enabled: false
        redis.embedded: false
        redis.enabled: false
